- name: Install Python on VM
  hosts: my_vm
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present
